spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # Preferred way to specify the dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

springfox:
  documentation:
    enabled: false
#logging:
#  level:
#    root: debug  # Set the root logger to debug
